### ISSUE TITLE
jsDocs checks failing?

### ISSUE THREAD

**Issue by ManitKSoni** [CSE112-SP22-TeamXRefactor/CSE112-SP22-TeamXRefactor#47] opened 2022-05-13 20:04 UTC
## Expected Behavior
Commits to main should pass the check for jsDocs.

## Actual Behavior
Due to authentication errors, commits to main generally seem to fail the jsDocs check.
Maybe because the jsDocs are hosted on another GitHub repository. Do we need to create our own jsDocs repo?

**Comment by Sasha45** [comment] 2022-05-16 22:06
Duplicate of #21

**Closed by Sasha45** 2022-05-16 22:06 UTC
Labels: bug, question
